name: Test App

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: |
          npm install yarn -g

      - name: install
        run: |
          yarn install

      - name: check types
        run: |
          yarn check-types

      - name: lint
        run: |
          yarn lint

      - name: test
        run: |
          yarn test
        env:
          CI: true
